sdr_parameters.vh:
	wget https://www.micron.com/~/media/documents/products/sim-model/dram/sdram/sdr_sdram.zip
	unzip sdr_sdram.zip
	rm sdr_sdram.zip

clean:
	rm -f readme.txt sdr_module.v sdr_parameters.vh sdr.v test.v
